# Configurações de postagem
pending_dir: "videos/pending"
posted_dir: "videos/posted"
# Horários (informativo) - o script não "agenda" por si só; rode-o via cron nestes horários:
scheduled_times:
  - "06:00"
  - "14:00"
  - "22:00"

# YouTube
youtube:
  category_id: "22"
  privacy: "public"   # public, unlisted, private

# Instagram
instagram:
  # credenciais: use variáveis de ambiente IG_ACCESS_TOKEN e IG_USER_ID

# Legendas: 3 opções (cada uma já com hashtags). O script escolhe 1 aleatoriamente.
captions:
  - "✨ Novo conteúdo chegando! Se curtiu, deixa o like e compartilha. #conteudo #shorts #reels #video"
  - "🚀 Mais um vídeo pra somar! Comenta o que você quer ver no próximo. #dicas #viral #shorts #reels"
  - "🔥 Doses de conteúdo diário — não perde! Ativa as notificações. #instavideo #shorts #reels #trending"

# Comportamento
move_after_post: true   # move de pending -> posted após publicar
require_both_platforms_success: false  # se true, move só quando BOTH forem sucesso
dry_run: false          # true para simular (sem calls reais)
