name: Post Reels & Shorts (scheduled)

on:
  schedule:
    # GitHub Actions usa UTC. Horários desejados no Brasil (BRT -03:00): 06:00, 14:00, 22:00
    # Convertendo para UTC: 09:00, 17:00, 01:00 -> lista 1,9,17 hora UTC
    - cron: '0 1,9,17 * * *'   # 01:00, 09:00, 17:00 UTC == 22:00, 06:00, 14:00 BRT
  workflow_dispatch: {}

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib requests

      - name: Download ngrok (stable)
        run: |
          # Baixa ngrok e coloca no PATH
          NGROK_VERSION="4.0.0" || true
          wget -q -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip -q ngrok.zip -d $HOME/ngrok
          sudo mv $HOME/ngrok/ngrok /usr/local/bin/ngrok
          ngrok version

      - name: Ensure directories exist
        run: |
          mkdir -p videos/pending videos/posted

      - name: Run posting script
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
          HTTP_SERVER_PORT: "8000"

          YOUTUBE_CLIENT_SECRET_JSON: ${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}
          YOUTUBE_TOKEN_PICKLE: ${{ secrets.YOUTUBE_TOKEN_PICKLE }} # Opcional: base64 do token.pickle
        run: |
          python3 post_all.py
