name: Post Shorts & Reels

on:
  schedule:
    # Executa às 06:00, 14:00 e 22:00 todos os dias
    - cron: "0 6,14,22 * * *"
  workflow_dispatch: # permite rodar manualmente também

jobs:
  post-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client requests

      - name: Instalar ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install -y ngrok

      - name: Configurar ngrok authtoken
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

        # upload para o yt aqui

      - name: Executar upload para Instagram
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
        run: |
          echo "🚀 Rodando upload para Instagram"
          python upload_instagram.py

      - name: Mover vídeos de pending para posted
        run: |
          echo "📂 Movendo vídeos processados"
          mkdir -p videos/posted
          for file in videos/pending/*; do
            if [ -f "$file" ]; then
              mv "$file" videos/posted/
              echo "✅ $file movido para videos/posted/"
            fi
          done

