name: Post Reels & Shorts (scheduled)

on:
  schedule:
    - cron: '0 1,9,17 * * *'  # UTC
  workflow_dispatch: {}

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-oauthlib requests

      - name: Install ngrok
        run: |
          wget -q -O ngrok.zip https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip -q ngrok.zip -d $HOME/ngrok
          sudo mv $HOME/ngrok/ngrok /usr/local/bin/ngrok
          ngrok version

      - name: Start ngrok
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          ngrok authtoken $NGROK_AUTHTOKEN
          nohup ngrok http 8000 --log=stdout > ngrok.log 2>&1 &
          echo "Aguardando ngrok iniciar..."
          sleep 10
          NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Ngrok público: $NGROK_URL"
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

      - name: Prepare folders
        run: |
          mkdir -p videos/pending videos/posted

      - name: Run posting script
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          HTTP_SERVER_PORT: "8000"
          YOUTUBE_CLIENT_SECRET_JSON: ${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}
          YOUTUBE_TOKEN_PICKLE: ${{ secrets.YOUTUBE_TOKEN_PICKLE }}
          NGROK_URL: ${{ env.NGROK_URL }}
        run: |
          python3 post_all.py
