name: Upload YouTube

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        run: |
          python3 -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client

      - name: Criar client_secret.json
        run: echo '${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}' > client_secret.json

      - name: Criar token.pickle
        run: echo '${{ secrets.YOUTUBE_TOKEN_PICKLE }}' | base64 --decode > token.pickle

      - name: Rodar upload YouTube
        run: python3 upload_youtube.py
