name: Upload Instagram & YouTube

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6,14,22 * * *"  # a cada 8h (06h, 14h, 22h UTC-3)

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Instala ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install ngrok -y

      - name: Autentica ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install google-auth-oauthlib google-api-python-client requests

      - name: Upload Instagram
        env:
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
        run: python3 upload_instagram.py