name: TikTok Selenium Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências do sistema (Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libgdk-pixbuf-2.0-0 \
            libgtk-3-0 \
            libasound2 \
            libx11-xcb1 \
            libxcomposite1 \
            libxrandr2 \
            libxi6 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            fonts-liberation \
            libu2f-udev \
            xdg-utils

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager python-dotenv

      - name: Executar bot TikTok
        env:
          TIKTOK_USERNAME: ${{ secrets.TIKTOK_USERNAME }}
          TIKTOK_PASSWORD: ${{ secrets.TIKTOK_PASSWORD }}
          HEADLESS: "true"
        run: |
          python upload_tiktok.py
