name: TikTok Selenium Upload

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Install Chrome (stable)
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb libnss3 libgconf-2-4
          wget -q -O chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i chrome.deb || sudo apt --fix-broken -y install
          google-chrome --version

      - name: Run script
        env:
          TIKTOK_USERNAME: ${{ secrets.TIKTOK_USERNAME }}
          TIKTOK_PASSWORD: ${{ secrets.TIKTOK_PASSWORD }}
          HEADLESS: ${{ secrets.HEADLESS }}  # "true" or "false"
        run: |
          # optional: set DISPLAY for chrome in headless CI
          export DISPLAY=:99
          Xvfb :99 -screen 0 1280x800x24 > /tmp/xvfb.log 2>&1 &

          ls -la
          echo "Running upload_tiktok.py (logs will print below)..."
          python upload_tiktok.py
